const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const state={results:[],compare:JSON.parse(localStorage.getItem("repolens_compare")||"[]"),saved:JSON.parse(localStorage.getItem("repolens_saved")||"[]"),token:localStorage.getItem("repolens_token")||"",lastQuery:""};
const api="https://api.github.com";
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
function toast(m){const t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove("show"),2800)}
function headers(){const h={"Accept":"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28"};if(state.token)h.Authorization=`Bearer ${state.token}`;return h}
function score(r){let s=50;if(r.description)s+=8;if(r.license)s+=6;if(r.homepage)s+=3;if(r.archived)s-=35;if(r.disabled)s-=45;if(r.forks_count>20)s+=7;if(r.stargazers_count>100)s+=7;if(r.open_issues_count<10)s+=5;const age=(Date.now()-new Date(r.updated_at))/86400000;if(age<30)s+=9;else if(age>365)s-=12;return Math.max(0,Math.min(100,Math.round(s)))}
function scoreClass(s){return s>=75?"good":s>=50?"mid":"low"}
function fmt(n){return Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1}).format(n||0)}
function repoCard(r){const s=score(r), selected=state.compare.some(x=>x.id===r.id), saved=state.saved.some(x=>x.id===r.id);return `<article class="repo">
<div><a class="repo-title" target="_blank" rel="noopener" href="${esc(r.html_url)}">${esc(r.full_name)}</a>
<p class="repo-desc">${esc(r.description||"No description provided.")}</p>
<div class="tags">${(r.topics||[]).slice(0,6).map(x=>`<span class="tag">${esc(x)}</span>`).join("")}</div>
<div class="repo-meta"><span>★ <b>${fmt(r.stargazers_count)}</b></span><span>⑂ <b>${fmt(r.forks_count)}</b></span><span>◉ <b>${esc(r.language||"—")}</b></span><span>↻ <b>${new Date(r.updated_at).toLocaleDateString()}</b></span></div></div>
<div class="repo-side"><div class="score ${scoreClass(s)}">${s}</div><div class="score-label">HEALTH SIGNAL</div><div class="repo-actions">
<button class="ghost-btn mini" data-action="compare" data-id="${r.id}">${selected?"✓ Compared":"＋ Compare"}</button>
<button class="ghost-btn mini" data-action="save" data-id="${r.id}">${saved?"★ Saved":"☆ Save"}</button></div></div></article>`}
async function search(q){q=q.trim();if(!q)return toast("Describe what you want to find.");state.lastQuery=q;$("#apiStatus").textContent="SYNC";$("#results").className="results";$("#results").innerHTML=`<div class="radar-card"><div class="radar"></div><div><h3>Searching GitHub…</h3><p>Turning your intent into repository signals.</p></div></div>`;try{const sort=$("#sortSelect").value;const url=`${api}/search/repositories?q=${encodeURIComponent(q)}&sort=${sort==="best-match"?"":sort}&order=desc&per_page=30`;const res=await fetch(url,{headers:headers()});if(!res.ok)throw new Error(`${res.status} ${res.statusText}`);const data=await res.json();state.results=data.items||[];renderResults();$("#apiStatus").textContent="LIVE";$("#resultCount").textContent=state.results.length}catch(e){$("#apiStatus").textContent="ERROR";$("#results").innerHTML=`<div class="results empty"><div class="empty-icon">!</div><h3>GitHub request failed</h3><p>${esc(e.message)}. Add a token if the public rate limit is exhausted.</p></div>`}}
function renderResults(){const box=$("#results");box.className="results";box.innerHTML=state.results.length?state.results.map(repoCard).join(""):`<div class="results empty"><h3>No repositories found</h3><p>Try a broader phrase.</p></div>`;$("#resultCount").textContent=state.results.length}
function persist(){localStorage.setItem("repolens_compare",JSON.stringify(state.compare));localStorage.setItem("repolens_saved",JSON.stringify(state.saved));updateCounts()}
function updateCounts(){$("#selectedCount").textContent=state.compare.length;$("#compareBadge").textContent=state.compare.length}
function handleAction(a,id){const r=state.results.find(x=>x.id===id)||state.saved.find(x=>x.id===id);if(!r)return;if(a==="compare"){if(state.compare.some(x=>x.id===id)){state.compare=state.compare.filter(x=>x.id!==id);toast("Removed from Compare Lab")}else{if(state.compare.length>=4)return toast("Compare Lab supports up to 4 repos.");state.compare.push(r);toast("Added to Compare Lab")}persist();renderResults();renderCompare()}else{if(state.saved.some(x=>x.id===id)){state.saved=state.saved.filter(x=>x.id!==id);toast("Removed from saved")}else{state.saved.push(r);toast("Saved locally")}persist();renderResults();renderSaved()}}
function renderCompare(){const b=$("#compareResults");b.innerHTML=state.compare.length?state.compare.map(r=>`<div class="compare-card"><h3>${esc(r.name)}</h3><p>${esc(r.description||"No description.")}</p><div class="compare-stat"><span>Health signal</span><b>${score(r)}/100</b></div><div class="compare-stat"><span>Stars</span><b>${fmt(r.stargazers_count)}</b></div><div class="compare-stat"><span>Forks</span><b>${fmt(r.forks_count)}</b></div><div class="compare-stat"><span>Issues</span><b>${fmt(r.open_issues_count)}</b></div><div class="compare-stat"><span>License</span><b>${esc(r.license?.spdx_id||"—")}</b></div><a class="ghost-btn mini" style="display:inline-block;margin-top:12px;text-decoration:none" target="_blank" href="${esc(r.html_url)}">Open repo ↗</a></div>`).join(""):`<div class="results empty"><h3>Nothing to compare</h3><p>Add up to four repositories from Smart Search.</p></div>`}
function renderSaved(){const b=$("#savedResults");b.innerHTML=state.saved.length?state.saved.map(repoCard).join(""):`<div class="results empty"><h3>Your library is empty</h3><p>Save useful repositories and they will stay in this browser.</p></div>`}
function nav(view){$$(".view").forEach(x=>x.classList.add("hidden"));$(`#${view}View`).classList.remove("hidden");$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.view===view));if(view==="compare")renderCompare();if(view==="saved")renderSaved()}
async function trending(){const topics=["ai agents","developer tools","automation","self hosted","observability"];const box=$("#trendingResults");box.innerHTML=`<div class="results empty"><div class="radar"></div><h3>Scanning ${topics.length} signals…</h3></div>`;let all=[];try{for(const t of topics){const r=await fetch(`${api}/search/repositories?q=${encodeURIComponent(t)}&sort=updated&order=desc&per_page=6`,{headers:headers()});if(r.ok){const d=await r.json();all.push(...(d.items||[]))}}const map=new Map(all.map(r=>[r.id,r]));state.results=[...map.values()].sort((a,b)=>score(b)-score(a));box.innerHTML=state.results.map(repoCard).join("");$("#resultCount").textContent=state.results.length;$("#apiStatus").textContent="LIVE"}catch(e){box.innerHTML=`<div class="results empty"><h3>Scan failed</h3><p>${esc(e.message)}</p></div>`}}
document.addEventListener("click",e=>{const q=e.target.closest("[data-q]");if(q){$("#searchInput").value=q.dataset.q;search(q.dataset.q)}const a=e.target.closest("[data-action]");if(a)handleAction(a.dataset.action,Number(a.dataset.id));const n=e.target.closest(".nav");if(n)nav(n.dataset.view)});
$("#searchBtn").onclick=()=>search($("#searchInput").value);$("#searchInput").addEventListener("keydown",e=>{if(e.key==="Enter")search(e.target.value)});
$("#trendBtn").onclick=trending;$("#clearCompare").onclick=()=>{state.compare=[];persist();renderCompare();renderResults()};$("#exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify(state.results,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="repolens-results.json";a.click();URL.revokeObjectURL(a.href)};
$("#tokenBtn").onclick=()=>{ $("#tokenInput").value=state.token;$("#tokenDialog").showModal()};$("#saveToken").onclick=()=>{state.token=$("#tokenInput").value.trim();localStorage.setItem("repolens_token",state.token);toast(state.token?"Token saved on this device.":"Token cleared.");};
$("#themeBtn").onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("repolens_light",document.body.classList.contains("light"))};
if(localStorage.getItem("repolens_light")==="true")document.body.classList.add("light");
setInterval(()=>$("#clock").textContent=new Date().toLocaleTimeString(),1000);updateCounts();renderSaved();renderCompare();
let deferredInstall=null;window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("#installBtn").classList.remove("hidden")});$("#installBtn").onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
window.addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="k"){e.preventDefault();$("#searchInput").focus()}});
